name: TTT
version: 0.1
author: iron42

main: de.iron42.TTT.TTT

commands:
  start:
    description: start
    usage: /start
  update:
    description: updates skull
    usage: /update
  stats:
    description: stats
    usage: /stats