name: TTT
version: 0.1
author: iron42

main: TTT.TTT

commands:
  start:
    description: start
    usage: /start
  update:
    description: updates skull
    usage: /update
  stats:
    description: stats
    usage: /stats
  packetsend:
    description: packet
    usage: /packetsend